; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = espidf
monitor_speed = 115200
upload_port = COM7
monitor_port = COM7
monitor_echo = yes
monitor_filters = direct
extra_scripts = fix_intellisense.py

;also change the image name here.
board_build.embed_files = 
    src/frame1.jpg
    src/frame2.jpg
    src/frame3.jpg
    src/frame4.jpg
    src/frame5.jpg
    src/frame6.jpg
    src/frame7.jpg
    src/frame8.jpg
    src/frame9.jpg
    src/frame10.jpg
    src/frame11.jpg
    src/frame12.jpg
    src/frame13.jpg
    src/frame14.jpg
    src/frame15.jpg
    src/left.jpg
    src/leftright.jpg
board_build.partitions = partitions.csv












